### ISSUE TITLE
mkdir: Cannot create directory '/lib/modules/6.5.0-17-generic/updates': Permission denied

### ISSUE THREAD

**Issue by nineSrn** [davidjo/snd_hda_macbookpro#117]
I followed the instruction: ./install.cirrus.driver.sh
Everything was fine until the last sentence showed up stated just like the title.
I cd and ls into /lib/modules/6.5.0-17-generic the updates folder in not there.

PS: Apologize in advance if this question is simple but I'm a newbie and noob trying to learn Linux. Thank you

**Comment by nineSrn** [comment]
Yep I'm a noob, the solution is to install it as root.

**Comment by osalbahr** [comment]
Glad you figured it out! Feel free to close the issue
