### ISSUE TITLE
How is this different from egorenar/snd-hda-codec-cs8409?

### ISSUE THREAD

**Issue by osalbahr** [davidjo/snd_hda_macbookpro#137]
How is this repo different from [Linux Kernel Sound Driver for Cirrus Logic CS8409 (e.g. for iMac27 5k)](https://github.com/egorenar/snd-hda-codec-cs8409)?

Is one a fork of the other?

- See also: https://github.com/egorenar/snd-hda-codec-cs8409/issues/12

**Comment by davidjo** [comment]
Yes - egorenar copied my repo when getting things to work for iMacs (which I dont have) - but now all the iMac additions have been replicated in my repo
