### ISSUE TITLE
Build Issue Manjaro 5.6

### ISSUE THREAD

**Issue by vvvilife** [davidjo/snd_hda_macbookpro#14]
https://pastebin.com/Ze0Bcsa7

Above is a copy of the terminal output when trying to run the .sh. This is on Manjaro with Linux Kernel 5.6.15-1-Manjaro.

**Comment by davidjo** [comment]
This may be fixed - missed a syntax correction for the edits in install.cirrus.driver.sh which are needed for 5.6 - so would work for other kernels but not 5.6.
(Ubuntu still does not seem to have a kernel package for 5.6)

**Comment by vvvilife** [comment]
Confirmed fixed. Thank you for your work in making Linux usable on Mac!

**Comment by Bicet** [comment]
It's still working also in 5.7 :+1:
