### ISSUE TITLE
implicit declaration of function ‘snd_hda_set_extended_codec_verb’

### ISSUE THREAD

**Issue by meeuw** [davidjo/snd_hda_macbookpro#3]
While building the sources from this repository I get the following warning:
`implicit declaration of function ‘snd_hda_set_extended_codec_verb’`

I cannot find any reference to `snd_hda_set_extended_codec_verb` used at: https://github.com/davidjo/snd_hda_macbookpro/blob/6368521fec26da09d13f835d5d13bc3430ea344c/patch_cirrus.c#L1862

**Comment by davidjo** [comment]
This was an attempt at a debugging function to hijack vendor defined commands  to call specific functions via hda-verb. In the end never really used - you can just remove it - Ill be pushing further updates in a few days in which Ill remove this.
