### ISSUE TITLE
Gnome 40 - 4 channel swapped

### ISSUE THREAD

**Issue by Bicet** [davidjo/snd_hda_macbookpro#30]
If I set the output to analog surround 4.0 output i got front right swapped with back left.
Is there something I can do?

**Comment by davidjo** [comment]
Look through issue #23 which worked through audio channel order issues.

In particular near the end  (Jan 6 2021) there are some patch files  to apply to the source code which changes the channel mapping from original Apple style  to a simpler 2 stereo pair style (which seems to fit much better into the linux way) - this may help.

**Comment by Bicet** [comment]
With the patch on this post: https://github.com/davidjo/snd_hda_macbookpro/issues/23#issuecomment-755484166

everything is ok now :)
