### ISSUE TITLE
Uninstalling the Driver

### ISSUE THREAD

**Issue by AlexMorello** [davidjo/snd_hda_macbookpro#32]
Hey folks, how do I uninstall the driver in its entirety, including _source_?

**Comment by AlexMorello** [comment]
> So the main script is install.cirrus.driver.sh which is a standard bash script in the git clone directory. You will also see a patch_cirrus directory. The patch applies to files in that directory. The command is patch (a very well known command) and you need to re-direct the patch file as the standard input. You may need to use the -p argument eg -p0 or -p1 or -pn if it says it cannot find files to be patched - googling should give you any info you need. Note that everything is done inside the git clone directory. Only the built module is copied out to the main kernel image folder (depending on distribution generally under /lib).

Thanks for taking your time, man, but I still don't quite follow. I've cloned the directory onto the machine and navigated to it in the terminal. ls yields the following: build install.cirrus.driver.sh NOTES.md patch_cirrus README.md tests. I now know how to instal the driver, but not how to patch it.

**Comment by AlexMorello** [comment]
> you need something like: patch -p0 <patch_imacs.diff.txt (assuming you place the patch_imacs.diff.txt file in the git clone directory). experiment with -p eg -p1 you could also go into the patch_cirrus directory and do patch -p0 <../patch_imacs.diff.txt After this then run install.cirrus.driver.sh

I've tried, but nothing happens. Just the blinking cursor indicative of a running process.

**Comment by davidjo** [comment]
Sorry - when I said -p0 this was just an example - you  need to try  eg -p1.
The error msg:
can't find file to patch at input line 11
Perhaps you used the wrong -p or --strip option?
is exactly what you get when it doesnt get the right -pX option - and does mean the command is running.
If you look in the patch_imacs.diff file you can see lines like
diff --git a/patch_cirrus/patch_cirrus_new84.h b/patch_cirrus/patch_cirrus_new84.h
what the -pX line does is remove portions of the path ie it looks for a file patch_cirrus/patch_cirrus_new84.h
So in fact you need -p1 to remove the a/ and b/ part of the path  -p0  leaves that in.
That is if you have the patch_imacs.diff in the git clone directory then
patch -p1 -i patch_imacs.diff.txt
should work when run in the git clone directory.

To remove as it looks like it never created the module just remove (recursively) the git clone directory and all sub directories

**Comment by davidjo** [comment]
The only thing it "installs" is the actual kernel module (it just copies the module snd-hda-codec-cirrus.ko into the main kernel module path under the updates directory).
Just remove this module from updates (see the Makefile in patch_cirrus directory).
A kernel source is downloaded into the build sub folder so will be removed when you remove the git clone directories.
There are no other dependencies.

**Comment by davidjo** [comment]
Please try the new version.
