### ISSUE TITLE
Error when building driver

### ISSUE THREAD

**Issue by danielsteman** [davidjo/snd_hda_macbookpro#39]
When I follow the instructions and run the install script, I run into the following error:

```
make -C /lib/modules/5.15.19-1-MANJARO/build CFLAGS_MODULE="-DCONFIG_SND_HDA_RECONFIG=1 -Wno-unused-variable -Wno-unused-function" M=/home/daniel/drivers/snd_hda_macbookpro/build/hda-5.15.19 modules
make[1]: *** /lib/modules/5.15.19-1-MANJARO/build: No such file or directory.  Stop.
make: *** [Makefile:17: all] Error 2
cp snd-hda-codec-cirrus.ko /lib/modules/5.15.19-1-MANJARO/updates
cp: cannot stat 'snd-hda-codec-cirrus.ko': No such file or directory
make: *** [Makefile:22: install] Error 1

contents of /lib/modules/5.15.19-1-MANJARO/updates
total 0
```

When I check the missing file path, there is no `build` or `updates`. I made sure to run the script as root by running `sudo ./install.cirrus.driver.sh`.

`inxi -Fazy`
System:
  Kernel: 5.15.19-1-MANJARO x86_64 bits: 64 compiler: gcc v: 11.1.0
    parameters: BOOT_IMAGE=/boot/vmlinuz-5.15-x86_64
    root=UUID=77b72e4b-789f-458d-b88b-71d361b6e8cf rw quiet apparmor=1
    security=apparmor udev.log_priority=3
  Desktop: KDE Plasma 5.23.5 tk: Qt 5.15.2 wm: kwin_x11 vt: 1 dm: SDDM
    Distro: Manjaro Linux base: Arch Linux
Machine:
  Type: Laptop System: Apple product: MacBookPro14,1 v: 1.0
    serial: <superuser required> Chassis: type: 9 v: Mac-B4831CEBD52A0C4C
    serial: <superuser required>
  Mobo: Apple model: Mac-B4831CEBD52A0C4C v: MacBookPro14,1
    serial: <superuser required> UEFI: Apple v: 429.140.8.0.0 date: 06/13/2021
Battery:
  ID-1: BAT0 charge: 51.6 Wh (100.0%) condition: 51.6/54.6 Wh (94.6%)
    volts: 12.9 min: 11.4 model: SMP bq20z451 type: Li-ion serial: N/A
    status: Full cycles: 23
  Device-1: hidpp_battery_0 model: Logitech Wireless Mouse MX Master 3
    serial: <filter> charge: 100% (should be ignored) rechargeable: yes
    status: Discharging
CPU:
  Info: model: Intel Core i5-7360U bits: 64 type: MT MCP arch: Amber/Kaby Lake
    note: check family: 6 model-id: 0x8E (142) stepping: 9 microcode: 0xEA
  Topology: cpus: 1x cores: 2 tpc: 2 threads: 4 smt: enabled cache:
    L1: 128 KiB desc: d-2x32 KiB; i-2x32 KiB L2: 512 KiB desc: 2x256 KiB
    L3: 4 MiB desc: 1x4 MiB
  Speed (MHz): avg: 700 min/max: 400/3600 scaling: driver: intel_pstate
    governor: powersave cores: 1: 700 2: 700 3: 700 4: 700 bogomips: 18406
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
  Vulnerabilities:
  Type: itlb_multihit status: KVM: VMX disabled
  Type: l1tf
    mitigation: PTE Inversion; VMX: conditional cache flushes, SMT vulnerable
  Type: mds mitigation: Clear CPU buffers; SMT vulnerable
  Type: meltdown mitigation: PTI
  Type: spec_store_bypass
    mitigation: Speculative Store Bypass disabled via prctl and seccomp
  Type: spectre_v1
    mitigation: usercopy/swapgs barriers and __user pointer sanitization
  Type: spectre_v2 mitigation: Full generic retpoline, IBPB: conditional,
    IBRS_FW, STIBP: conditional, RSB filling
  Type: srbds mitigation: Microcode
  Type: tsx_async_abort mitigation: TSX disabled
Graphics:
  Device-1: Intel Iris Plus Graphics 640 vendor: Apple driver: i915 v: kernel
    bus-ID: 00:02.0 chip-ID: 8086:5926 class-ID: 0300
  Display: x11 server: X.org 1.21.1.3 compositor: kwin_x11 driver:
    loaded: modesetting alternate: fbdev,vesa resolution: <missing: xdpyinfo>
  Message: Unable to show advanced data. Required tool glxinfo missing.
Audio:
  Device-1: Intel Sunrise Point-LP HD Audio driver: snd_hda_intel v: kernel
    alternate: snd_soc_skl bus-ID: 00:1f.3 chip-ID: 8086:9d71 class-ID: 0403
  Device-2: Broadcom 720p FaceTime HD Camera driver: N/A bus-ID: 03:00.0
    chip-ID: 14e4:1570 class-ID: 0480
  Sound Server-1: ALSA v: k5.15.19-1-MANJARO running: yes
  Sound Server-2: JACK v: 1.9.20 running: no
  Sound Server-3: PulseAudio v: 15.0 running: yes
  Sound Server-4: PipeWire v: 0.3.45 running: yes
Network:
  Device-1: Broadcom BCM4350 802.11ac Wireless Network Adapter vendor: Apple
    driver: brcmfmac v: kernel bus-ID: 02:00.0 chip-ID: 14e4:43a3 class-ID: 0280
  IF: wlp2s0 state: up mac: <filter>
Drives:
  Local Storage: total: 113 GiB used: 11.46 GiB (10.1%)
  SMART Message: Unable to run smartctl. Root privileges required.
  ID-1: /dev/nvme0n1 maj-min: 259:0 vendor: Apple model: SSD AP0128J
    size: 113 GiB block-size: physical: 4096 B logical: 4096 B speed: 31.6 Gb/s
    lanes: 4 type: SSD serial: <filter> rev: 16.14.01 temp: 37.9 C scheme: GPT
  ID-2: /dev/nvme0n2 maj-min: 259:3 vendor: Apple model: SSD AP0128J
    size: 8 KiB block-size: physical: 4096 B logical: 4096 B speed: 31.6 Gb/s
    lanes: 4 type: SSD serial: <filter> rev: 16.14.01 temp: 37.9 C
Partition:
  ID-1: / raw-size: 112.65 GiB size: 110.32 GiB (97.93%)
    used: 11.46 GiB (10.4%) fs: ext4 dev: /dev/nvme0n1p2 maj-min: 259:2
  ID-2: /boot/efi raw-size: 300 MiB size: 299.3 MiB (99.76%)
    used: 288 KiB (0.1%) fs: vfat dev: /dev/nvme0n1p1 maj-min: 259:1
Swap:
  Alert: No swap data was found.
Sensors:
  System Temperatures: cpu: 53.0 C mobo: N/A
  Fan Speeds (RPM): N/A
Info:
  Processes: 203 Uptime: 55m wakeups: 4 Memory: 7.63 GiB
  used: 2.12 GiB (27.8%) Init: systemd v: 250 tool: systemctl Compilers:
  gcc: 11.1.0 clang: 13.0.0 Packages: pacman: 1223 lib: 332 flatpak: 0
  Shell: Zsh v: 5.8 default: Bash v: 5.1.16 running-in: konsole inxi: 3.3.12

**Comment by davidjo** [comment]
Im not sure I can help - this is not a distribution I have used and its quite a recent kernel and there have been a number of issues with kernels from 5.12 including actual kernel source changes which cause build errors and require changes to this repo (last kernel Ive built is 5.11 but my main kernel is still 5.4).
At the moment the primary issue seems to be the missing /lib/modules/5.15.19-1-MANJARO/build.
On Ubuntu 20.04 this is a symbolic link to a kernel headers source package for the kernel version specified which needs to be installed explicitly eg linux-headers-5.4.0-92-generic for me in your case should be linux-headers-5.15.19-1-generic if manjaro kernel packaging is similar to Ubuntu.
