### ISSUE TITLE
major changes with 1.18.*?

### ISSUE THREAD

**Issue by slynobody** [davidjo/snd_hda_macbookpro#50]
You should take a look at kernel 5.18. (really usable changes systemwide!), whichs begins to pop up in major distributions currently.

The script throws out 3 new 'error' messages while compiling now. and while the errors seem not be severe ( some things seem not to be declared properly, you should have corrected it in a minute) the context is interesting: a whole zoology of different chip-types, amps and codes now ( this seemed to be not there in 5.17). Somehow the kernel itself seem to converge in your direction? 

Hopefully you can alter the script soon. Just try a current kernel for fun for a few minutes, try the script and take a look at the errors. Realy, realy interesting. 
Otherwise currently the script will not work anymore for anyone with a kernel after 5.17 anymore. Hope you fix this very soon.

**Comment by davidjo** [comment]
Updated build script to use patch command - which gets rid of build error as seen in png file.

**Comment by carrelebo** [comment]
with the Zen Kernel (lastest version 5.18.7) everything is working :)

It can be a problem with the original kernel.
